### PR TITLE
Bug 1649642 - Add moments page schema and enforce validation for bucket and message id

### PR DESCRIPTION
**Pull request by piatra**
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1649642

tldr: Aim is to make it easier to identify messages in telemetry analysis with their corresponding branch and experiment.

### CODE REVIEW

**Comment by piatra** [comment]
This got a little more complicated than I expected because of the variation that exists:
1. Experiments with 1 message per branch (CFR): this is easy to handle
2. Experiments with multiple messages per branch (about welcome cards):
  * this is the 3 card selection shown on about:welcome for new profiles
  * clicking on one send telemetry with message_id as identifier
  * still ok to handle, we discussed that id is a union of branch+message_id
3. Experiments with multiple messages per branch and an identifier for the group (new onboarding experience):
  * different from (2) because now the 3 cards are associated in a group with an id
  * the telemetry sent is `group_id+message_id`

For (3) should we set the `group_id` to match the branch so that way the ping reported is in the expected `branch+message`? I don't personally like this because you can't "grep" for the id you see in telemetry if you want to look something up, this happens with snippets and it's annoying when you need it.
Is (2) going away/being replaced by (3)? Having 1 less "special case" might make it easier to move forward.

cc @punamdahiya @ncloudioj to validate / discuss this.

**Comment by ncloudioj** [comment]
Looks like bug 1649642 only cares about the CFR (maybe also moments) experiments, do we need this for other experiments as well?

I believe (3) has already replaced (2) as the default first-run experience in Nightly 80, so we can just focus on (3) now. Also, the `message_ids` in (3) are dynamically assigned in the browser, we might not be able to enforce that over here.

Lastly, we should consider porting this to Experimenter at some point as eventually, all the experiments will be made over there.

**Comment by piatra** [comment]
@tdsmith is this for CFR experiments only?

**Comment by tdsmith** [comment]
That's a great question!

In general I'd love to associate a message with the experiment and branch that caused it to be shown, for all message types. I'm most acutely interested in CFR since we need to do automated analysis for it in the short run but we'll need to solve this for other message types as we build out for them.

It's possible it's easier to extend the probes in some different way compared to stuffing values into the fields we already have.

**Comment by piatra** [comment]
I think this is ready for review @ncloudioj

**Comment by ncloudioj** [comment]
@piatra could you list the proposed naming conventions for each experiment group? I believe @tdsmith and @punamdahiya should also review this to ensure everyone is on the same page.

Note that eventually this should also be implemented in Experimenter.

**Comment by piatra** [comment]
It should be:
* bucket_id matching the experiment slug
* message_id matching the branch name
Where a branch has multiple messages I went with `[branch, id]` like `"['treatment-variation-d','TRAILHEAD_CARD_3']"`

**Comment by ncloudioj** [comment]
> It should be:
> 
>     * bucket_id matching the experiment slug
> 
>     * message_id matching the branch name
> 
> Where a branch has multiple messages I went with `[branch, id]` like `"['treatment-variation-d','TRAILHEAD_CARD_3']"`

The `[branch, id]` part might have some issue for about:welcome metrics, as it already uses a dynamic naming scheme internally. Also, those metrics are shared with Amplitude, this would make it harder to use. 

@tdsmith is this what you're expecting?

@punamdahiya I believe you've mentioned there are some telemetry asks from DS for about:welcome. Could you also take a look at this change, please?

Alternatively, we can just apply this change to CFR experiments for now, as the about:welcome changes/requirements are still under discussion. @piatra what do you think?

**Comment by tdsmith** [comment]
> @tdsmith is this what you're expecting?

That solution is acceptable to me, but I don't insist on it; sending a new telemetry event or adding fields to the existing messages makes sense to me if other systems are already relying on the current behavior.

**Comment by piatra** [comment]
I think we're going to close this in favor of having Experimenter take the responsibility. Given the edge cases we will rely on slug from Experimenter & reviews to enforce the correct names.

**Pull request closed without merging**
